---
title: "Case Study 11"
author: Marko Lazin
date: November 19, 2020
output: html_document
---

##Package Setup
```{r, warning=FALSE,message=FALSE,}
library(tidyverse)
library(spData)
library(sf)

library(mapview)
library(foreach)
library(doParallel)
registerDoParallel(4)
#getDoParWorkers()
library(tidycensus)
```

```{r,results=FALSE,message=FALSE,warning=FALSE}
racevars<-c(White="P005003", 
            Black="P005004", 
            Asian="P005006", 
            Hispanic="P004003")
options(tigris_use_cache=TRUE)
erie<-get_decennial(geography="block",
                    variables=racevars,
                    state="NY",
                    county="Erie County",
                    geometry=TRUE,
                    summary_var="P001001",
                    cache_table=TRUE)%>%
  st_crop(c(xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.948))
```

```{r,warning=FALSE,message=FALSE}
race_points<-foreach(race=unique(erie$variable),.combine=rbind) %dopar% {
  race_erie=filter(erie,variable==race)
  race_sample=st_sample(race_erie,size=race_erie$value)
  race_sf=st_as_sf(race_sample)
  mutate(race_sf,race=race)
}
my_palette<-c("salmon","violet","turquoise","yellow")
mapview(race_points,cex=1,lwd=0.01,alpha=.9,col.regions=my_palette)
```




